### ISSUE TITLE
./configure fails in qemu-virgl.rb

### ISSUE THREAD

**Issue by jkoiv** [akirakyle/homebrew-qemu-virgl#10]
The sed command on line 90 needs to be e.g.:

```
    system "sed", "-i", ".orig", "-e", "/emulator = executable/ a\\ 
               install_rpath: '/opt/homebrew/lib', 
", "meson.build"
```

Otherwise meson.build fails when running ./configure. With this and the revision fix in #9 everything builds, at least on MacOS 12.6.3 and current versions of dependencies.

**Comment by akirakyle** [comment]
I'm not planning to maintain this going forward. Please see my update in the README.
