### ISSUE TITLE
 Update revision in git url in qemu-virgl.rb formula to fix git checkout err 128 fatal: reference is not a tree

### ISSUE THREAD

**Issue by porteusconf** [akirakyle/homebrew-qemu-virgl#9]
To fix brew error (further below) I had to `brew edit akirakyle/qemu-virgl/qemu-virgl` and manually update the revision to "388aa42d3ae9d1a4cfbb6a41e5fe59c52079384a" in line 5 of [homebrew-qemu-virgl](https://github.com/akirakyle/homebrew-qemu-virgl)/[Formula/qemu-virgl.rb](https://github.com/akirakyle/homebrew-qemu-virgl/tree/master/Formula/qemu-virgl.rb) as shown below. And thank you for all the great work! Hope your qemu/tree/macos is upstreamed soon, as well as work to support qemu on ios at https://github.com/utmapp/qemu/releases. I am using UTM.app on macos (and ios), and I think I will not need to `brew unlink qemu-virgl` as it seems UTM.app uses sandbox, but we will see ;-)
```
class QemuVirgl < Formula
  desc "Emulator for x86 and PowerPC"
  homepage "https://www.qemu.org/"
  # waiting for upstreaming of https://github.com/akihikodaki/qemu/tree/macos
  # url "https://github.com/akihikodaki/qemu.git", using: :git, revision: "ec003996725787cc169cc49ace0326f5ff3464e6"
  url "https://github.com/akihikodaki/qemu.git", using: :git, revision: "388aa42d3ae9d1a4cfbb6a41e5fe59c52079384a"
  version "20221230.1"
  license "GPL-2.0-only"

  bottle do
    root_url "https://github.com/akirakyle/homebrew-qemu-virgl/releases/download/2023-01-18"
    rebuild 1
    sha256 arm64_ventura: "354b81d36f405a91bf6ecdf2be86a8f596da8126b7f8845c002363ef1b4a0e96"
  end
...
```

Changing git URL as shown below got rid of error below from brew on my intel mac running monterey 12.6.3:
``` shell
%  brew install --fetch-HEAD  akirakyle/qemu-virgl/qemu-virgl
...
==> Cloning https://github.com/akihikodaki/qemu.git
Updating /Users/student/Library/Caches/Homebrew/qemu-virgl--git
==> Checking out revision ec003996725787cc169cc49ace0326f5ff3464e6
fatal: reference is not a tree: ec003996725787cc169cc49ace0326f5ff3464e6
Error: qemu-virgl: Failed to download resource "qemu-virgl"
Failure while executing; `/usr/bin/env git checkout -f ec003996725787cc169cc49ace0326f5ff3464e6 --` exited with 128. Here's the output:
fatal: reference is not a tree: ec003996725787cc169cc49ace0326f5ff3464e6
```
I also tried `brew install --HEAD  akirakyle/qemu-virgl/qemu-virgl`

**Comment by akirakyle** [comment]
I'm not planning to maintain this going forward. Please see my update in the README.
